### ISSUE TITLE
Využité technológie

### ISSUE THREAD

**Issue by Krajcovic70** [TIS2024-FMFI/smelyzajko-gui#2]

**Comment by pavelpetrovic** [comment]
Ako poslat kanvas, do ktoreho modul aplikacie moze kreslit svoj graficky obsah:

https://chatgpt.com/share/671f93f3-1d90-8011-8ca9-9ec44eda1585

**Comment by pavelpetrovic** [comment]
neviem, ci to shareovanie nie je nejake rozbite. mne to zobrazilo "regenerate" a potom uz zas napisal trochu ine veci...  ale ved opytajte sa ho asi radsej sami.


Hello! ImGui can indeed support this kind of architecture with a bit of custom handling. By default, ImGui itself doesn’t provide a direct mechanism to manage custom canvas objects in the way you described, but it does support the creation of custom drawing surfaces through its ImDrawList and related utilities. Here are some suggestions for integrating it into your framework:
1. Using ImDrawList for Immediate Mode Drawing

ImGui’s ImDrawList is the primary tool for drawing lines, shapes, and text. By providing a handle to a custom canvas object, you could wrap an ImDrawList instance so the user module can draw directly on it. You can acquire the ImDrawList object for the current frame by calling ImGui::GetWindowDrawList() if you’re working within a window, or ImGui::GetForegroundDrawList() for drawing on the screen-level foreground.

cpp

ImDrawList* draw_list = ImGui::GetWindowDrawList();
draw_list->AddLine(ImVec2(x1, y1), ImVec2(x2, y2), IM_COL32(255, 0, 0, 255), 1.0f);

2. Custom Canvas Object Wrapping ImDrawList

You could create a canvas class that holds a reference to an ImDrawList. This class can serve as a user-accessible API for drawing operations, abstracting away some of ImGui’s lower-level details. Here’s a simple example of what that might look like:

cpp

class Canvas {
public:
    Canvas(ImDrawList* drawList) : drawList(drawList) {}

    void DrawLine(float x1, float y1, float x2, float y2, ImU32 color, float thickness) {
        drawList->AddLine(ImVec2(x1, y1), ImVec2(x2, y2), color, thickness);
    }

    // Additional drawing methods...
private:
    ImDrawList* drawList;
};

You can then create a Canvas instance with ImGui::GetWindowDrawList() and pass this as a handle to the user’s module for drawing.
3. Offscreen Rendering with Framebuffers

For more complex scenarios, where you may want to draw on an offscreen buffer, you could consider setting up a framebuffer object (FBO) with OpenGL or DirectX, depending on your rendering backend. ImGui doesn’t manage framebuffers directly, but you can integrate an FBO rendering process with ImGui by binding the FBO before issuing draw calls. Once you’re done drawing to the FBO, you can display it within ImGui using ImGui::Image().
4. Integrating ImGui with a Custom Rendering Backend

Since ImGui is renderer-agnostic, you can integrate it with any backend you prefer, including OpenGL, DirectX, or Vulkan. You could render your ImGui canvas elements using your rendering context and pass it as a texture to ImGui, allowing the user to draw on that custom canvas while still using ImGui’s drawing tools.

Would any of these approaches fit your design? Let me know if you’d like more details on a specific part!
